"""Repository ports (protocols) for the Identity context."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from app.modules.identity.infrastructure.models import RefreshToken, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def update_last_login(self, user_id: uuid.UUID, when: datetime) -> None: ...
    async def list_role_codes(self, user_id: uuid.UUID) -> list[str]: ...


class RefreshTokenRepository(Protocol):
    async def create(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_id(self, token_id: uuid.UUID) -> RefreshToken | None: ...
    async def revoke(self, token_id: uuid.UUID, *, replaced_by: uuid.UUID | None = None) -> None: ...
    async def revoke_family(self, family_id: uuid.UUID) -> None: ...
