"""Reusable model mixins: UUID PK, timestamps, soft delete, audit."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database.types import UUIDType, UUID_DEFAULT_SQL


class UUIDPrimaryKeyMixin:
    """Adds a UUID v4 primary key generated by Postgres (`gen_random_uuid()`)."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUIDType,
        primary_key=True,
        server_default=UUID_DEFAULT_SQL,
    )


class TimestampMixin:
    """Adds `created_at` / `updated_at` timezone-aware columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class SoftDeleteMixin:
    """Logical deletion. Concrete repositories must filter by `is_deleted=false`."""

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )
    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="false",
        index=True,
    )


class AuditMixin:
    """Tracks which user created / last-updated a row. Set by the service layer."""

    created_by: Mapped[uuid.UUID | None] = mapped_column(UUIDType, nullable=True)
    updated_by: Mapped[uuid.UUID | None] = mapped_column(UUIDType, nullable=True)
